import { albums } from "@/features/album";
import { Song } from "../types/Song";

export const songs: Song[] = [
  {
    id: "1",
    title: "Starlit Serenade",
    getAlbum: () => albums[0],
    duration: "3:45",
  },
  {
    id: "2",
    title: "Whispers of Tomorrow",
    getAlbum: () => albums[1],
    duration: "4:18",
  },
  {
    id: "3",
    title: "Dancing in Moonlight",
    getAlbum: () => albums[2],
    duration: "4:02",
  },
  {
    id: "4",
    title: "Eternal Embrace",
    getAlbum: () => albums[3],
    duration: "3:30",
  },
  {
    id: "5",
    title: "Sunset Reverie",
    getAlbum: () => albums[4],
    duration: "3:56",
  },
  {
    id: "6",
    title: "Melodies of Dawn",
    getAlbum: () => albums[5],
    duration: "4:10",
  },
  {
    id: "7",
    title: "Midnight Mirage",
    getAlbum: () => albums[6],
    duration: "3:52",
  },
  {
    id: "8",
    title: "Celestial Symphony",
    getAlbum: () => albums[7],
    duration: "4:15",
  },
  {
    id: "9",
    title: "Falling Leaves",
    getAlbum: () => albums[8],
    duration: "3:48",
  },
  {
    id: "10",
    title: "Lost in Sound",
    getAlbum: () => albums[9],
    duration: "3:59",
  },
  {
    id: "11",
    title: "Mystic Echoes",
    getAlbum: () => albums[10],
    duration: "4:25",
  },
  {
    id: "12",
    title: "Harbor of Dreams",
    getAlbum: () => albums[11],
    duration: "3:40",
  },
  {
    id: "13",
    title: "Ocean's Lullaby",
    getAlbum: () => albums[0],
    duration: "3:55",
  },
  {
    id: "14",
    title: "Serenade of Stars",
    getAlbum: () => albums[1],
    duration: "4:12",
  },
  {
    id: "15",
    title: "Raindrop Melodies",
    getAlbum: () => albums[2],
    duration: "4:08",
  },
  {
    id: "16",
    title: "Enchanted Voyage",
    getAlbum: () => albums[3],
    duration: "3:45",
  },
  {
    id: "17",
    title: "Ripples of Reflection",
    getAlbum: () => albums[4],
    duration: "3:30",
  },
  {
    id: "18",
    title: "Echoes of Solitude",
    getAlbum: () => albums[5],
    duration: "4:22",
  },
  {
    id: "19",
    title: "Whispering Breeze",
    getAlbum: () => albums[6],
    duration: "3:58",
  },
  {
    id: "20",
    title: "Twilight Waltz",
    getAlbum: () => albums[7],
    duration: "4:05",
  },
  {
    id: "21",
    title: "Chasing Horizons",
    getAlbum: () => albums[8],
    duration: "3:42",
  },
  {
    id: "22",
    title: "Ethereal Euphony",
    getAlbum: () => albums[9],
    duration: "4:30",
  },
  {
    id: "23",
    title: "Frozen in Time",
    getAlbum: () => albums[10],
    duration: "3:48",
  },
  {
    id: "24",
    title: "Luminous Nocturne",
    getAlbum: () => albums[11],
    duration: "4:08",
  },
  {
    id: "25",
    title: "Crimson Serenade",
    getAlbum: () => albums[0],
    duration: "3:55",
  },
  {
    id: "26",
    title: "Harmonic Meadows",
    getAlbum: () => albums[1],
    duration: "4:10",
  },
  {
    id: "27",
    title: "Dreamer's Reverie",
    getAlbum: () => albums[2],
    duration: "3:38",
  },
  {
    id: "28",
    title: "Cascade of Dreams",
    getAlbum: () => albums[3],
    duration: "4:25",
  },
  {
    id: "29",
    title: "Aurora Melodies",
    getAlbum: () => albums[4],
    duration: "3:48",
  },
  {
    id: "30",
    title: "Phoenix Rising",
    getAlbum: () => albums[5],
    duration: "4:15",
  },
  {
    id: "31",
    title: "Silent Whispers",
    getAlbum: () => albums[6],
    duration: "3:52",
  },
  {
    id: "32",
    title: "Solitary Melancholy",
    getAlbum: () => albums[7],
    duration: "4:02",
  },
  {
    id: "33",
    title: "Moonlit Rhapsody",
    getAlbum: () => albums[8],
    duration: "3:40",
  },
  {
    id: "34",
    title: "Whirlwind of Emotions",
    getAlbum: () => albums[9],
    duration: "3:59",
  },
  {
    id: "35",
    title: "Stardust Serenade",
    getAlbum: () => albums[10],
    duration: "4:12",
  },
  {
    id: "36",
    title: "Enchanted Carousel",
    getAlbum: () => albums[11],
    duration: "3:45",
  },
  {
    id: "37",
    title: "Crystal Clear",
    getAlbum: () => albums[0],
    duration: "4:08",
  },
  {
    id: "38",
    title: "Astral Ballad",
    getAlbum: () => albums[1],
    duration: "3:48",
  },
  {
    id: "39",
    title: "Journey Beyond",
    getAlbum: () => albums[2],
    duration: "4:18",
  },
  {
    id: "40",
    title: "Cerulean Skies",
    getAlbum: () => albums[3],
    duration: "4:30",
  },
  {
    id: "41",
    title: "Lost in the Echo",
    getAlbum: () => albums[4],
    duration: "3:30",
  },
  {
    id: "42",
    title: "Symphony of Shadows",
    getAlbum: () => albums[5],
    duration: "4:05",
  },
  {
    id: "43",
    title: "Twinkling Stars",
    getAlbum: () => albums[6],
    duration: "3:58",
  },
  {
    id: "44",
    title: "Reverie in Rain",
    getAlbum: () => albums[7],
    duration: "4:22",
  },
  {
    id: "45",
    title: "Sapphire Serenity",
    getAlbum: () => albums[8],
    duration: "3:55",
  },
  {
    id: "46",
    title: "Whispered Secrets",
    getAlbum: () => albums[9],
    duration: "3:45",
  },
  {
    id: "47",
    title: "Tranquil Oasis",
    getAlbum: () => albums[10],
    duration: "4:18",
  },
  {
    id: "48",
    title: "Harbor Lights",
    getAlbum: () => albums[11],
    duration: "3:52",
  },
];
